package net.alteiar.lendyr.model.persona;

public enum AbilityFocus {
  // Accuracy Focuses
  ARCANE_BLAST, BLACK_POWDER, BOWS, BRAWLING, DUELING, GRENADES, LIGHT_BLADES, STAVES, SLINGS,

  // Communication Focuses
  ANIMAL_HANDLING, BARGAINING, DECEPTION, DISGUISE, ETIQUETTE, GAMBLING, INVESTIGATION, LEADERSHIP, PERFORMANCE, PERSUASION, SEDUCTION,

  // Constitution Focuses
  ROWING, RUNNING, STAMINA, SWIMMING, TOLERANCE,

  // Dexterity Focuses
  ACROBATICS, CALLIGRAPHY, CRAFTING, INITIATIVE, LEGERDEMAIN, LOCK_PICKING, RIDING, SAILING, STEALTH, TRAPS,

  // Fighting Focuses
  AXES, BLUDGEONS, HEAVY_BLADES, LANCES, POLEARMS, SPEARS,

  // Intelligence Focuses
  ARCANA, ARCANE_LORE, BREWING, CARTOGRAPHY, CRYPTOGRAPHY, CULTURAL_LORE, ENGINEERING, EVALUATION, HEALING, HERALDRY,
  HISTORICAL_LORE, MILITARY_LORE, MUSICAL_LORE, NATURAL_LORE, NAVIGATION, RELIGIOUS_LORE, RESEARCH, THIEVES_LORE, WRITING,

  // Perception Focuses
  EMPATHY, HEARING, SEARCHING, SEEING, SMELLING, TASTING, TOUCHING, TRACKING,

  // Strength Focuses
  CLIMBING, DRIVING, INTIMIDATION, JUMPING, MIGHT, SMITHING,

  // Willpower Focuses
  COURAGE, FAITH, MORAL, SELF_DISCIPLINE
}
