package net.alteiar.lendyr.model.persona;

import lombok.Getter;

import java.util.List;

import static net.alteiar.lendyr.model.persona.AbilityFocus.*;

@Getter
public enum Ability {
  ACCURACY(List.of(ARCANE_BLAST, BLACK_POWDER, BOWS, BRAWLING, DUELING, GRENADES, LIGHT_BLADES, STAVES, SLINGS)),
  COMMUNICATION(List.of(ANIMAL_HANDLING, BARGAINING, DECEPTION, DISGUISE, ETIQUETTE, GAMBLING, INVESTIGATION, LEADERSHIP, PERFORMANCE, PERSUASION, SEDUCTION)),
  CONSTITUTION(List.of(ROWING, RUNNING, STAMINA, SWIMMING, TOLERANCE)),
  DEXTERITY(List.of(ACROBATICS, CALLIGRAPHY, CRAFTING, INITIATIVE, LEGERDEMAIN, LOCK_PICKING, RIDING, SAILING, STEALTH, TRAPS)),
  FIGHTING(List.of(AXES, BLUDGEONS, HEAVY_BLADES, LANCES, POLEARMS, SPEARS)),
  INTELLIGENCE(List.of(ARCANA, ARCANE_LORE, BREWING, CARTOGRAPHY, CRYPTOGRAPHY, CULTURAL_LORE, ENGINEERING, EVALUATION, HEALING, HERALDRY,
      HISTORICAL_LORE, MILITARY_LORE, MUSICAL_LORE, NATURAL_LORE, NAVIGATION, RELIGIOUS_LORE, RESEARCH, THIEVES_LORE, WRITING)),
  PERCEPTION(List.of(EMPATHY, HEARING, SEARCHING, SEEING, SMELLING, TASTING, TOUCHING, TRACKING)),
  STRENGTH(List.of(CLIMBING, DRIVING, INTIMIDATION, JUMPING, MIGHT, SMITHING)),
  WILLPOWER(List.of(COURAGE, FAITH, MORAL, SELF_DISCIPLINE));

  private final List<AbilityFocus> focusList;

  private Ability(List<AbilityFocus> focusList) {
    this.focusList = focusList;
  }
}
